apiVersion: v1
kind: Service
metadata:
  name: svc-lb
  namespace: kiran
spec:
  type: LoadBalancer
  selector:
    app: caddy
  ports:
  - port: 80  #service port inside cluster
    targetPort: 80 #container port
